version: "3.9"

services:
  elastic:
    image: elasticsearch:8.1.0
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - esdata:/usr/share/elasticsearch/data


    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
      - xpack.security.enabled=true
    networks:
      - reverseproxy-nw

  kibana:
    image: kibana:8.1.0
    ports:
      - 5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data

    environment:
      - ELASTICSEARCH_URL=http://elastic:9200

    depends_on:
      - elastic
    networks:
      - reverseproxy-nw


networks:
  reverseproxy-nw:
    external: true


volumes:
  esdata:
    driver: local
  kibanadata:
    driver: local
